// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1920","screenHeight":"1080","changeWindowWidthTo":"1280","changeWindowHeightTo":"720","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Chronus","status":true,"description":"ゲーム内時間の導入プラグイン","parameters":{"月ごとの日数配列":"31,28,31,30,31,30,31,31,30,31,30,31","月名配列":"1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月","曜日配列":"(日),(一),(二),(三),(四),(五),(六)","自然時間加算":"1","自然時間加算間隔":"60","場所移動時間加算":"30","戦闘時間加算(固定)":"30","戦闘時間加算(ターン)":"5","年のゲーム変数":"21","月のゲーム変数":"22","日のゲーム変数":"23","曜日IDのゲーム変数":"0","曜日名のゲーム変数":"0","時のゲーム変数":"0","分のゲーム変数":"0","累計時間のゲーム変数":"0","累計日数のゲーム変数":"0","時間帯IDのゲーム変数":"0","天候IDのゲーム変数":"0","フォーマット時間の変数":"0","フォーマット時間の計算式":"HH24 * 60 + MI","日時フォーマット1":"YYYY年 MM月 DD日 DY","日時フォーマット2":"AMHH時 MI分","日時フォーマット行間":"0","カレンダー表示X座標":"1608","カレンダー表示Y座標":"2","カレンダーフォントサイズ":"0","カレンダー不透明度":"192","カレンダー枠の非表示":"false","カレンダーの非表示":"false","カレンダー余白":"8","文字盤画像ファイル":"","長針画像ファイル":"","短針画像ファイル":"","時計X座標":"84","時計Y座標":"156","イベント中時間経過":"false"}}
];
